/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.cxrus.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Articles service. Represents a row in the &quot;AR_Articles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cxrus.model.impl.ArticlesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cxrus.model.impl.ArticlesImpl}.
 * </p>
 *
 * @author mohdtaufik
 * @see Articles
 * @see com.cxrus.model.impl.ArticlesImpl
 * @see com.cxrus.model.impl.ArticlesModelImpl
 * @generated
 */
public interface ArticlesModel extends BaseModel<Articles>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a articles model instance should use the {@link Articles} interface instead.
	 */

	/**
	 * Returns the primary key of this articles.
	 *
	 * @return the primary key of this articles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this articles.
	 *
	 * @param primaryKey the primary key of this articles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this articles.
	 *
	 * @return the uuid of this articles
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this articles.
	 *
	 * @param uuid the uuid of this articles
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the articles ID of this articles.
	 *
	 * @return the articles ID of this articles
	 */
	public long getArticlesId();

	/**
	 * Sets the articles ID of this articles.
	 *
	 * @param articlesId the articles ID of this articles
	 */
	public void setArticlesId(long articlesId);

	/**
	 * Returns the group ID of this articles.
	 *
	 * @return the group ID of this articles
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this articles.
	 *
	 * @param groupId the group ID of this articles
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this articles.
	 *
	 * @return the company ID of this articles
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this articles.
	 *
	 * @param companyId the company ID of this articles
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this articles.
	 *
	 * @return the user ID of this articles
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this articles.
	 *
	 * @param userId the user ID of this articles
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this articles.
	 *
	 * @return the user uuid of this articles
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this articles.
	 *
	 * @param userUuid the user uuid of this articles
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this articles.
	 *
	 * @return the user name of this articles
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this articles.
	 *
	 * @param userName the user name of this articles
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this articles.
	 *
	 * @return the create date of this articles
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this articles.
	 *
	 * @param createDate the create date of this articles
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this articles.
	 *
	 * @return the modified date of this articles
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this articles.
	 *
	 * @param modifiedDate the modified date of this articles
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the article name of this articles.
	 *
	 * @return the article name of this articles
	 */
	@AutoEscape
	public String getArticleName();

	/**
	 * Sets the article name of this articles.
	 *
	 * @param articleName the article name of this articles
	 */
	public void setArticleName(String articleName);

	/**
	 * Returns the article title of this articles.
	 *
	 * @return the article title of this articles
	 */
	@AutoEscape
	public String getArticleTitle();

	/**
	 * Sets the article title of this articles.
	 *
	 * @param articleTitle the article title of this articles
	 */
	public void setArticleTitle(String articleTitle);

	/**
	 * Returns the published date of this articles.
	 *
	 * @return the published date of this articles
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this articles.
	 *
	 * @param publishedDate the published date of this articles
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Returns the category articles ID of this articles.
	 *
	 * @return the category articles ID of this articles
	 */
	public long getCategoryArticlesId();

	/**
	 * Sets the category articles ID of this articles.
	 *
	 * @param categoryArticlesId the category articles ID of this articles
	 */
	public void setCategoryArticlesId(long categoryArticlesId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.cxrus.model.Articles articles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.cxrus.model.Articles> toCacheModel();

	@Override
	public com.cxrus.model.Articles toEscapedModel();

	@Override
	public com.cxrus.model.Articles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}